language: dart

dart:
  - 2.2.0
  - dev

dart_task:
  - dartanalyzer: --fatal-warnings --fatal-lints .

matrix:
  include:
    - dart: dev
      dart_task: dartfmt
    - dart: dev
      dart_task:
        test: -x presubmit-only
    - dart: dev
      dart_task:
        test: --run-skipped -t presubmit-only

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
   - .dart_tool/
