name: peanut
version: 3.0.0-dev
description: >-
  Update your GitHub gh-pages branch with the compiled output of your Dart web
  app. Supports 'pub build' and the new 'pub run build_runner'.
author: Kevin Moore <github@j832.com>
homepage: https://github.com/kevmoo/peanut.dart
environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  args: ^1.5.1
  build_cli_annotations: ^1.0.0
  git: ^0.5.1
  glob: ^1.1.5
  io: ^0.3.2+1
  json_annotation: ^2.2.0
  meta: ^1.0.0
  path: ^1.3.4
  pub_semver: ^1.4.0
  yaml: ^2.1.0

dev_dependencies:
  build_cli: ^1.0.0
  build_runner: ^1.0.0

  # build_web_compilers is here to support the `example` dir
  build_web_compilers: '>=1.0.0 <=2.0.0-alpha.2'

  json_serializable: ^2.2.1
  pedantic: ^1.3.0
  test: ^1.6.0
  test_descriptor: ^1.1.1
  test_process: ^1.0.1

executables:
  peanut: peanut
